server:
  serverName: commservice-notice
  logKeep: 7
  heartbeat: 60
  httpPort: 8008 #8003
  https: false
  timeout: 30
  #日志打印方式，0：打印到控制台，1打印到txt文件  zk
  logRecord: true
  ReadTimeout: 60
  WriteTimeout: 60
  logSavePath: storage/logs #日志保存路径  zk
  logFileSize: 5 #单个日志文件大小单位(M)   yuan:5
  logFileCount: 10 #日志文件保留个数       yuan:10
  logLevel: 2 #日志等级 0:不打印日志,1:只打印err日志，2：打印全部日志
  logMode: 0 #日志打印方式，0：打印到控制台，1打印到txt文件
  fileExpireTime: 30 #冗余文件清理时间（单位天）
  fileCleanTime: 720 #执行冗余文件清理时间间隔（单位分钟）

Ali:
  AccessKeyId: LTAI4FnjHfoFomah6s5vbUEm
  AccessKeySecret: Bp150bRDD30Tkoo9KgsmPCFG2L2g5w
  AccessKeyIdVoice: LTAI5tPe7KYqG8QKx82Uh6tE
  AccessKeySecretVoice: p9w1rQNSO0pknbTgtcnA0MuQP8epzn
  #邮件端点
  EndpointDm: dm.aliyuncs.com
  #短信端点
  EndpointDysms: dysmsapi.aliyuncs.com
  #语音端点
  EndpointVoice: dyvmsapi.aliyuncs.com

#极光推送
urora:
  appKey: 3c419c716a46d165f98b8f3d
  masterSecret: c2afeffc2dbe50b28c4dcecd
  url: https://api.jpush.cn/v3/push

ngiot:
  addr: https://api-ngiot.dc-cn.cn.ecouser.net
  baseUrl: https://users-base.dc-cn.cn.ecouser.net
  clientId: 618dc1c3c3d79b9b59ed2f11
  clientSecret: 1f86ba6be8bd43f2899274c37bf0182e
  user: admin
  password: 0290532c5b2e0d1d8773aeb6db664845
  resource: web
  country: CN
  opt:
  challengeType: app
  challengeSecret: 12345

database:
  addr: postgresql://root:robotdb@10.91.26.225:2625/ffplat_2
  maxIdleConns: 10

nats:
  connect: nats://10.91.26.225:4222,nats://10.91.26.226:4222,nats://10.91.26.227:4222
  name: service-noticeserver
  timeout: 10
  pingInterval: 20
  maxPingsOutstanding: 5
  maxReconnects: 10
  reconnectWait: 10
  reconnectBufSize: 5
  userName: ffpdb2.0
  passWord: he8846mh

SSDB:
  Addr: 10.91.26.225:8886
  Addr1: 10.91.26.225:8887
  Password:
  DB: 0
  PoolSize: 30
  MinIdleConns: 30
